Allow constructing subclass of abstract class
google/autocxx pull request #1206
Opened 2023-01-15 20:38 UTC by russelltg

Fixes #774

I have a solid start here, but I think I'm going to need some guidance to get this complete. I have it all working except overloads, and I need to somehow get the C++ types of the arguments from an `Api<FnPrePhase2>`

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

2023-01-16 12:31 UTC, adetaylor commented
Thanks for having a stab at this! Looks to be along the right lines, and good job figuring out the convoluted codebase well enough to get this in the right places.

> I need to somehow get the C++ types of the arguments from an Api<FnPrePhase2>

`FnAnalysis::params` is what you need. This contains the Rust types, but they're "converted", which means we have things like `UniquePtr<Foo>` rather than whatever bindgen gave us. Therefore the `syn::Type`s in that field are essentially canonical and can be relied upon to uniquely represent C++ types; they should be good enough for overload resolution. 
 i.e. Rather than compare `QualifiedName`s, you should compare `syn::Type`s, which is what you'll find in this location.

I'm not going to take a more detailed look at this until the tests are green and you tell me that it's good to go. Good luck!

2023-01-18 04:35 UTC, russelltg commented
Thanks for the help there, I've figured out the resolution stuff. 

The only missing thing is it doesn't really support pure virtual dtors in either the base or the sub class. I don't think pure virtual dtors get passed to the analysis? Or at least I don't see it.

2023-01-18 04:45 UTC, russelltg commented
I'm going to go ahead and mark this as ready for review, as I think it's useful and correct as is. I'm happy to deal with the pure virtual dtor edgecase if you think that's important/worthwhile.

2023-01-19 15:11 UTC, adetaylor commented
Thanks, I'm travelling right now so I'm unlikely to take a look at this for a few days, but I'll get there.

2023-01-29 09:03 UTC, adetaylor requested changes
Sorry for the delay on reviewing this.

It's looking great!

My comments are:
* a load of nit picks and suggestions
* one substantial comment that I can't easily follow what happens in cases where our data structures are incomplete (for unforeseen reasons) - I want to make sure we're erring on the side of regarding classes as abstract. I'm sure I could figure it out by peering more carefully at it, but the fact it's hard to follow suggests it could do with a little bit more in the way of comments.

2023-01-29 09:03 UTC, adetaylor commented on integration-tests/tests/integration_test.rs
> +        //     ~Partial5() = 0;
Totally happy not to address this case now, but please could you add a comment in this test case explaining why this is commented out.

2023-01-29 09:03 UTC, adetaylor commented on integration-tests/tests/integration_test.rs
> +        //     ~Partial5() = 0;
(also if you could file a new github issue that'd be great)

2023-01-29 09:03 UTC, adetaylor commented on integration-tests/tests/integration_test.rs
> +        static_assertions::assert_impl_all!(ffi::FullyDefined: moveit::CopyNew);
I wish I'd thought of using this for loads of the other tests!

2023-01-30 04:20 UTC, russelltg commented
`fields_and_bases_first` is super cool, thanks for pointing me there, that *significnatly* simplifies the code. The only problem....it doesn't seem to actually do bases first? It's definitely emitting the `Struct` api's before the methods.....

I suppose the name is evident--it's fields and bases first not fields, methods, and bases first. I think the cleanest way to fix this would be to either have a new traverser that does to methods first (or just edit fields_and_bases_first to do that) or just go through the API list twice like I was doing previously

2023-01-30 10:13 UTC, adetaylor commented
> I suppose the name is evident--it's fields and bases first not fields, methods, and bases first. I think the cleanest way to fix this would be to either have a new traverser that does to methods first (or just edit fields_and_bases_first to do that)

Originally it did do this, but it turned out this caused cycles, because (I think) some types of constructor need to depend on the type they're constructing. You'd be most welcome to try to solve this but I think it was Hard. (I can't remember the details). So going through the list twice is probably best.

2023-01-30 10:16 UTC, adetaylor commented on engine/src/conversion/apivec.rs
> +        self.apis.iter_mut()
Oh, I'm really sorry, I offered you bad advice here. `iter_mut` is considered harmful here for the reasons explained in this comment:
https://github.com/google/autocxx/pull/1206/files/8d4d785f4105c3332b1f77f8f0c0756ef9e72545..c90cd896eca376977c87e04707ec48ba01b243bd#diff-dd61892ff96d055fbcab83c5eecc76c8b6120c3eb2f1b5687a8c025435200fcdL32
I just plain forgot! Sorry for the rework.

2023-01-30 10:18 UTC, adetaylor commented on engine/src/conversion/analysis/abstract_types.rs
> +        match dbg!(api) {
Don't forget to remove this dbg

2023-02-09 17:56 UTC, russelltg commented
This is ready for review @adetaylor  :)

2023-02-17 16:09 UTC, adetaylor commented
I'm good to merge this once the formatting problems are fixed!

2023-02-20 10:13 UTC, adetaylor commented
Thanks very much for this!

2023-02-20 10:13 UTC, merged